Add files via upload
makefile: new
memgrind.c: no changes from master branch
mymalloc.c: Two changes. Line 50: commented out "result = NULL;". Caused an error saying it was undefined. Line 127: changed "big_block->free = 0" to "big_block->empty = 0;"

When I run the make file I get this as an error:

mymalloc.o:(.data+0x0): multiple definition of `initList'
/tmp/cck4xY25.o:(.data+0x0): first defined here
mymalloc.o:(.data+0x8): multiple definition of `magic_yes'
/tmp/cck4xY25.o:(.data+0x8): first defined here
mymalloc.o:(.data+0xc): multiple definition of `magic_no'
/tmp/cck4xY25.o:(.data+0xc): first defined here
collect2: error: ld returned 1 exit status
make: *** [all] Error 1